title: Hanif Fahreza
logo: /assets/img/image.jpg
description: Hello There! I am hanif fahreza, I am a freshgraduate from industrial engineering at diponegoro university. 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
